application: feed-cleaner
version: 3
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /googled5216d7987aee3d4.html
  static_files: static/googled5216d7987aee3d4.html
  upload: static/googled5216d7987aee3d4.html

- url: /.*
  script: djangoappengine/main/main.py
